spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/newsletterdb
    username: newsletterdb-user
    password: newsletterdb-password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: newsletter
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/newsletterapi
server:
  port: 8081

