version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: newsletterdb-user
      POSTGRES_PASSWORD: newsletterdb-password
      POSTGRES_DB: newsletterdb
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "8080:8080"
